

version: 2

models:
  - name: cc_stock
    columns:
      ### PK ###
      - name: product_id
        tests:
          - not_null
          - unique
      - name: product_name
        tests:
          - not_null
      - name: model_type
        tests:
          - accepted_values:
                values: ["T-shirt", "Short", "Legging", "Crop-top", "Top", "Accessories"]